
POST http://localhost:8000/register
Content-Type: application/json

{
  "firstname": "Wonder",
  "lastname": "woman",
  "email": "wonder@woman.com",
  "password": "password"
}

###

POST http://localhost:8000/signin
Content-Type: application/json

{
  "email": "sper@man.com",
  "password": "password"
}

###

GET http://localhost:8000/api/client/596060f69797ed2d0c4a0070
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhdEBtYW4uY29tIiwiaWF0IjoxNDk5NDk0MDQyLCJleHAiOjE0OTk1MTU2NDIsInN1YiI6IjU5NWY3N2FjOWU1MWRlMTI2OWIwYWZkMSJ9.SSwK3e9GHmFiLrQKyQZXCLUd8dEkZzj4BHk132SIo8Uhhq
