
GET http://localhost:8000/api/client/59698017712d55056b3d5910

###

POST http://localhost:8000/api/client/new
content-type: application/json

{
    "firstname": "Adrian",
    "lastname": "Hobbs",
    "phonenumber": "0416034878",
    "email": "jaime@something.com"
}

###

PUT http://localhost:8000/client/595cfa6cef8d4c07e900a483
content-type: application/json

{
  "firstname": "Chris",
    "lastname": "knobetson",
    "phonenumber": "0416034878",
    "email": "jaime@something.com",
    "status": {
      "phonecall": false,
      "email": false,
      "depositCleared": false
    }
}

###

DELETE http://localhost:8000/api/client/59698017712d55056b3d5910

###

GET http://localhost:8000/api/clients