
GET http://localhost:8000/api/client/596060fc9797ed2d0c4a0071

###

POST http://localhost:8000/api/client/new
content-type: application/json

{
    "firstname": "Jaime",
    "lastname": "Terreu",
    "phonenumber": "0416034878",
    "email": "jaime@something.com",
    "status": {
      "phonecall": false,
      "email": false,
      "depositCleared": false
    }
}

###

PUT http://localhost:8000/client/595cfa6cef8d4c07e900a483
content-type: application/json

{
  "firstname": "Chris",
    "lastname": "knobetson",
    "phonenumber": "0416034878",
    "email": "jaime@something.com",
    "status": {
      "phonecall": false,
      "email": false,
      "depositCleared": false
    }
}

###

DELETE http://localhost:3000/client/595cfa6cef8d4c07e900a483

###

GET http://localhost:8000/api/clients