GET http://localhost:3000/messages/595cfa6cef8d4c07e900a483
###
POST http://localhost:3000/message/new
content-type: application/json

{
    "message": "Guys a tool",
    "for": "595cfa6cef8d4c07e900a483",
    "from": "595c87721bf2fd11256d870c"
}
