
POST http://localhost:8000/api/settings/new
Content-Type: application/json

{
  "bitfinexFloat": 0,
  "btceFloat": 0,
  "bitstampFloat": 0
}

###

PATCH http://localhost:8000/api/settings/59642ab99039a21b6839c24e
content-type: application/json

{
    "bitfinexFloat": "20000",
    "btceFloat": "25000",
    "bitstampFloat": "22000",
    "ethWalletAddress": "0x7e14C106cc04e19734F882793b82c751C21f4495",
    "btceWalletAddress": "12boeZKpPs6zcAN9w1bzgyRfa7iQ5Uw471"
}

###

GET http://localhost:8000/api/ethereumBalance

###

GET http://localhost:8000/api/bitcoinBalance