GET http://localhost:3000/users
###
POST http://localhost:3000/user/new
content-type: application/json

{
    "firstname": "Chris",
    "lastname": "Robertson"
}

###

DELETE http://localhost:3000/user/595c7a1baa92d60d88650773
